general.import = [
  "~/.config/alacritty/hosts/current.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 100
color = "#ffa000"

[font]
  normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
  # set per-host
  # size = 14.0

[env]
  term = "xterm-direct"

[window]
  decorations = "Buttonless"

[window.padding]
  x = 10
  y = 10

[colors]
  draw_bold_text_with_bright_colors = true

[colors.primary]
  foreground = "#c9c9c9"
  background = "#012B36"
  bright_foreground = "#95a0a0"

[colors.normal]
  black = "#163540"
  red = "#f54e4e"
  green = "#8dba2d"
  yellow = "#ae8a2c"
  blue = "#4689cc"
  magenta = "#c24380"
  cyan = "#519e97"
  white = "#ece8d6"

[colors.dim]
  black = "#0d2a34"
  red = "#bc5329"
  green = "#5c6d74"
  yellow = "#697a81"
  blue = "#869395"
  magenta = "#6c70be"
  cyan = "#95a0a0"
  white = "#fbf6e4"


# Key bindings
[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "None"

